## 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np
a = np.random.random((3,3,3))
print(a)



[[[0.82699374 0.71600997 0.27529785]
  [0.80110201 0.30735586 0.30219793]
  [0.11613168 0.03120749 0.7058587 ]]

 [[0.04624397 0.20729072 0.37866581]
  [0.23298635 0.36608935 0.05965489]
  [0.12250401 0.9744327  0.61523457]]

 [[0.06293544 0.29537581 0.83839152]
  [0.08339976 0.06766946 0.88647199]
  [0.74186452 0.83384327 0.28348643]]]


## 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [1]:
import numpy as np
d = np.diag([1, 2, 3, 4, 5])
print(d)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


## 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
x = np.ones((3,3))

x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 4.Normalize a 5x5 random matrix

In [4]:
import numpy as np
x= np.random.random((5,5))
print("Random Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Random Array:
[[0.6201205  0.36072985 0.61008529 0.02189379 0.51905683]
 [0.90647445 0.99875488 0.61118202 0.29700289 0.29453742]
 [0.83434287 0.12052609 0.20135298 0.10333929 0.69879511]
 [0.89381418 0.57333518 0.25150778 0.54036588 0.08555166]
 [0.33586406 0.90210763 0.52055145 0.1068443  0.584709  ]]
After normalization:
[[0.61239691 0.34686207 0.60212399 0.         0.50893934]
 [0.90553372 1.         0.6032467  0.28162561 0.27910174]
 [0.83169356 0.10096861 0.18371004 0.0833747  0.69293508]
 [0.89257357 0.56450338 0.23505286 0.53075314 0.06516574]
 [0.32140728 0.90106346 0.51046936 0.08696273 0.57614661]]


## 5.How to find common values between two arrays?

In [5]:
import numpy as np
array1 = np.array([110, 120, 130, 140, 160])
print("Array1: ",array1)
array2 = [110, 130, 400]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [110 120 130 140 160]
Array2:  [110, 130, 400]
Common values between two arrays:
[110 130]


## 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


## 7.Consider two random array A and B, check if they are equal


In [7]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 0 0 1]
Second array:
[0 0 1 1 1 0]
Test above two arrays are equal or not!
False


## 8.Create random vector of size 10 and replace the maximum value by 0


In [8]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)


Original array:
[0.63595809 0.28350649 0.38430256 0.10009157 0.59816931 0.51820164
 0.03193574 0.26307969 0.38311894 0.86769459]
Maximum value replaced by 0:
[0.63595809 0.28350649 0.38430256 0.10009157 0.59816931 0.51820164
 0.03193574 0.26307969 0.38311894 0.        ]


## 9.How to print all the values of an array?

In [13]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(len(a)):
    print(a[i])

1
2
3
4
5
6
7
8
9
10


## 10.Subtract the mean of each row of a matrix

In [14]:
import numpy as np
print("Original matrix:\n")
X = np.array([[10,20,30],[34,56,76]])
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[10 20 30]
 [34 56 76]]

Subtract the mean of each row of the said matrix:

[[-10.           0.          10.        ]
 [-21.33333333   0.66666667  20.66666667]]


## 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [25]:
import numpy as np
z=np.ones(10)
a=np.random.randint(0,len(z),20)
z+=np.bincount(a,minlength=len(z))
print(z)

[4. 2. 3. 2. 3. 1. 4. 2. 2. 7.]


## 12.How to get the diagonal of a dot product?

In [31]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.diag(x.dot(x.T))
print(y)


[ 14  77 194]


In [30]:

import numpy as np
s=1
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(3):
    for j in range(3):
        if i==j:
            s=s*a[i][j]
print(s)


45


## 13.How to find the most frequent value in an array?

In [15]:
import numpy as np
x = np.array([1,2,3,4,4,4,5,6,7,8,3,2,1,89,76,54,34,34,3,5,34,3,4])
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[ 1  2  3  4  4  4  5  6  7  8  3  2  1 89 76 54 34 34  3  5 34  3  4]
Most frequent value in the above array:
3


## 14.How to get the n largest values of an array

In [21]:
import numpy as np
x=np.arange(45)
print(x)
np.random.shuffle(x)
n=1
print(x[np.argsort(x)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
[44]


## 15.How to create a record array from a regular array?

In [16]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)


In [26]:
import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9]])
i=np.diag(x.dot(x.T))
print(i)



[ 14  77 194]
